"""empty message

Revision ID: aa29582d15cf
Revises: 1fa6d0be4b2d
Create Date: 2020-01-21 07:05:44.614759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa29582d15cf'
down_revision = '1fa6d0be4b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_genres')
    op.drop_table('venue_genres')
    op.add_column('Artist', sa.Column(
        'genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column(
        'genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_table('Genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    op.create_table('venue_genres',
                    sa.Column('venue_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('genre_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['genre_id'], ['Genre.id'], name='venue_genres_genre_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['venue_id'], ['Venue.id'], name='venue_genres_venue_id_fkey'),
                    sa.PrimaryKeyConstraint('venue_id', 'genre_id',
                                            name='venue_genres_pkey')
                    )
    op.create_table('Genre',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='Genre_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('artist_genres',
                    sa.Column('artist_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('genre_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['Artist.id'], name='artist_genres_artist_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['genre_id'], ['Genre.id'], name='artist_genres_genre_id_fkey'),
                    sa.PrimaryKeyConstraint('artist_id', 'genre_id',
                                            name='artist_genres_pkey')
                    )
    # ### end Alembic commands ###
